### ISSUE TITLE
Error (větev nepimach_general), když se pokusím vejít do minihry tak to vyhodí error

### ISSUE THREAD

**Issue by Ailta** [sps-trutnov/projekt-1ep-shawshank#93]
`Traceback (most recent call last):
  File "E:\sadsa\Škola\Python\next\projekt-1ep-shawshank\src\main.py", line 887, in <module>
    health = play_minigame()
  File "E:\sadsa\Škola\Python\next\projekt-1ep-shawshank\src\main.py", line 159, in play_minigame
    outcome = random.choice(minigames).main(language)
TypeError: main() takes 0 positional arguments but 1 was given`

ale čas od času se nestane takže se to asi děje při tom když se chce spustit určitá minihra

minihry: 
<module 'udatny' from 'E:\\sadsa\\Škola\\Python\\next\\projekt-1ep-shawshank\\src\\minihry\\udatny.py'>
             <module 'serbousek' from 'E:\\sadsa\\Škola\\Python\\next\\projekt-1ep-shawshank\\src\\minihry\\serbousek.py'>
             <module 'svoboda' from 'E:\\sadsa\\Škola\\Python\\next\\projekt-1ep-shawshank\\src\\minihry\\svoboda.py'>
             <module 'langer' from 'E:\\sadsa\\Škola\\Python\\next\\projekt-1ep-shawshank\\src\\minihry\\langer.py'>
             <module 'pospisil' from 'E:\\sadsa\\Škola\\Python\\next\\projekt-1ep-shawshank\\src\\minihry\\pospisil.py'>

**Comment by nepimachv21** [comment]
Pokusím se opravit.

**Comment by senkyr** [comment]
Vypadá to dobře. Mergnul jsem to zatím do _develop_ pro další testování.

Pod jakým číslem verze budeme chtít lokalizaci vydat? @nepimachv21

**Comment by nepimachv21** [comment]
Nevím zda je nějaký postup na animacích, které jsou plánovány do milestonu v1.1, ale pokud ano, tak bych lokalizaci zařadil do stejného milestonu. V případě, že na animacích není žádný postup bych buď animace posunul např. do verze 1.2, aby lokalizace mohla být ve verzi 1.1, nebo bychom mohli udělat něco jako verzi 1.0.5

**Comment by senkyr** [comment]
Zní to dobře, rád bych ale nejdřív provedl zevrubnější testování.
